"""
retriever.py
------------
Implements the two-stage hybrid retrieval strategy at the core of this RAG chatbot.

Stage 1 – Q/A Store lookup (fast, low-latency):
    The user's question is encoded into an embedding and compared against all
    pre-generated Q/A pairs using vector similarity.  If the best match meets or
    exceeds HYBRID_THRESHOLD (default 0.75) the stored answer is returned directly,
    no LLM call needed.  This keeps latency low for common questions.
    Note: match quality depends on Q/A dataset quality (auto-generated by LLM)
    and the threshold, which has not been formally evaluated.

Stage 2 – Doc Store fallback (broad, context-rich):
    When no Q/A pair is confident enough, the retriever falls back to a semantic
    search over the full scraped document chunks.  The top-K chunks are returned
    to the chatbot, which feeds them into the LLM to synthesise a grounded answer.

Return contract
---------------
Both stages return the same dict shape so the caller (chatbot.py) needs no
branching logic on the retrieval side:
    {
        "mode":             "qa_match" | "doc_search",
        "answer":           str | None,
        "source":           str | None,
        "matched_question": str | None,
        "confidence":       float,          # LangChain euclidean relevance score [0, 1]; NOT cosine similarity
        "context_docs":     list[Document], # non-empty only for doc_search
    }
"""

import logging
import os
import sys
from typing import Any

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import HYBRID_THRESHOLD, TOP_K_DOCS

from langchain_core.documents import Document
from src.vector_store import load_doc_store, load_qa_store

logger = logging.getLogger(__name__)


class HybridRetriever:
    """
    Orchestrates the two-stage hybrid retrieval pipeline.

    Attributes
    ----------
    doc_store : Chroma
        Vector store containing chunked raw documentation pages.
        Used as the RAG fallback when no Q/A match is found.
    qa_store : Chroma
        Vector store containing the pre-generated Q/A dataset.
        Each document holds a question as page_content and the
        corresponding answer + source URL in its metadata.
    """

    def __init__(self):
        logger.info("Loading vector stores...")
        # Both stores are loaded once at startup and kept in memory for the
        # lifetime of the application to avoid repeated disk I/O.
        self.doc_store = load_doc_store()
        self.qa_store = load_qa_store()
        logger.info("Retriever ready.")

    # ------------------------------------------------------------------
    # Stage 1 – Q/A semantic search
    # ------------------------------------------------------------------

    def search_qa_store(self, query: str, top_k: int = 1) -> list[tuple[Document, float]]:
        """
        Encode *query* and retrieve the most similar Q/A pairs from the
        Q/A vector store, together with their relevance scores.

        Parameters
        ----------
        query : str
            The raw user question.
        top_k : int
            Number of candidate pairs to return (default 1 — we only need
            the single best match for the confidence check).

        Returns
        -------
        list of (Document, float)
            Each tuple contains a Q/A Document and a relevance score in [0, 1].
            Score is computed as ``1 - L2_distance / sqrt(2)`` (LangChain default
            for L2-indexed stores with normalised embeddings) — not cosine similarity.
        """
        results = self.qa_store.similarity_search_with_relevance_scores(query, k=top_k)
        return results

    # ------------------------------------------------------------------
    # Stage 2 – Doc semantic search (RAG fallback)
    # ------------------------------------------------------------------

    def search_doc_store(self, query: str, top_k: int | None = None) -> list[Document]:
        """
        Encode *query* and retrieve the top-K most relevant document chunks
        from the scraped documentation store.

        These chunks are passed verbatim to the LLM as grounding context,
        so a higher top_k gives the LLM more material but also increases
        token cost and latency.  TOP_K_DOCS (config) is the default.

        Parameters
        ----------
        query : str
            The raw user question.
        top_k : int, optional
            Override the default TOP_K_DOCS setting.

        Returns
        -------
        list[Document]
            Ranked document chunks (most similar first).
        """
        if top_k is None:
            top_k = TOP_K_DOCS
        return self.doc_store.similarity_search(query, k=top_k)

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def retrieve(self, query: str) -> dict[str, Any]:
        """
        Execute the full two-stage hybrid retrieval for a user query.

        Decision logic
        --------------
        1. Search the Q/A store and inspect the best relevance score
           (LangChain euclidean-based, [0, 1]; see search_qa_store docstring).
        2. If score >= HYBRID_THRESHOLD  →  return the stored answer directly
           (mode = "qa_match").  No LLM call is needed.
        3. Otherwise  →  fall back to the doc store and return the top-K
           context chunks for the LLM to synthesise an answer
           (mode = "doc_search").

        Parameters
        ----------
        query : str
            The raw user question as typed in the chat UI.

        Returns
        -------
        dict
            See module-level docstring for the full return contract.
        """
        # --- Stage 1: Q/A lookup ---
        qa_results = self.search_qa_store(query, top_k=1)
        best_score = qa_results[0][1] if qa_results else 0.0
        best_doc   = qa_results[0][0] if qa_results else None

        if best_score >= HYBRID_THRESHOLD:
            if best_doc is None:
                raise RuntimeError("qa_results was non-empty but best_doc is None — unexpected state.")
            # Score meets threshold — return the pre-generated answer.
            # The matched_question field is exposed in the UI so users can see
            # which stored question was considered equivalent to their query.
            return {
                "mode":             "qa_match",
                "answer":           best_doc.metadata.get("answer", ""),
                "source":           best_doc.metadata.get("source", ""),
                "matched_question": best_doc.page_content,
                "confidence":       best_score,
                "context_docs":     [],
            }

        # --- Stage 2: RAG fallback ---
        # No Q/A match met the threshold (or QA store is empty) — retrieve raw
        # document chunks and let the LLM synthesise a grounded answer.
        context_docs = self.search_doc_store(query)
        return {
            "mode":             "doc_search",
            "answer":           None,          # LLM generates this in chatbot.py
            "source":           None,
            "matched_question": None,
            "confidence":       best_score,    # score of the rejected QA match (not doc relevance)
            "context_docs":     context_docs,
        }

